---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "mediator-agent.fullname" . }}-data
  labels: {{- include "mediator-agent.labels" . | nindent 4}}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: netapp-file-standard
  resources:
    requests:
      storage: 128Mi

