# Default values for attestation-controller.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

autoscaling:
  enabled: false

podAnnotations: {}
podLabels: {}

image:
  pullPolicy: Always
  registry: artifacts.developer.gov.bc.ca/docker-remote
  repository: postgres
  tag: "13"

netpol:
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: c2a2c4-dev

resources:
  requests:
    memory: 92Mi
    cpu: 20m
  limits:
    memory: 92Mi
    cpu: 100m

imagePullSecrets:
  - name: artifactory-regcred

service:
  targetPort: 5432

# env:
#   POSTGRES_DATABSE: mediator
